---
- hosts: localhost
  roles:
    - role: ssh-config
      ssh_proxies:
        - alias: dev-director
          address: 10.41.210.1
          username: stack
          jump_username: stackhpc
          jump_address: xcat1-wcdc.hpc.cam.ac.uk
        - alias: stg-director
          address: 10.121.100.250
          username: stack
          jump_username: stackhpc
          jump_address: xcat1-wcdc.hpc.cam.ac.uk
