---
- name: Ensure that SSH hosts are configured
  blockinfile:
    block: |
      {% for host in ssh_hosts %}
      Host {{ host.pattern }}
        User {{ host.username }}
        HostName {{ host.address }}
      {% if host.proxy is defined %}
        ProxyCommand ssh {{ host.proxy.username }}@{{ host.proxy.address }} -W {{ host.address }}:%p
      {% endif %}
      {% for lf in host.local_forwards | default([]) %}
        LocalForward {% if lf.local_host is defined %}{{ lf.local_host }}:{% endif %}{{ lf.local_port }} {{ lf.remote_host }}:{{ lf.remote_port }}
      {% endfor %}
      {% endfor %}
    dest: "{{ ansible_user_dir }}/.ssh/config"
    state: present
    create: yes
