---
- name: Ensure that SSH proxy jump hosts are configured
  blockinfile:
    block: |
      {% for proxy in ssh_proxies %}
      Host {{ proxy.alias }}
        User {{ proxy.username }}
        ProxyCommand ssh {{ proxy.jump_username }}@{{ proxy.jump_address }} -W {{ proxy.address }}:%p
      {% endfor %}
    dest: "{{ ansible_user_dir }}/.ssh/config"
    state: present
    create: yes
